travis:
  secure:
    BINSTAR_TOKEN: UYVquyFygGtFE0lH7PXCf6M6sH2dJDQkBII/pIzYU7uLJNhqCR4HPNMBUyctOslWI/kunchEV4EO9V8VXt76G0SSO02A86R2h7OB1j+VmdGrfbGo4BSKKfLvIfZflVWg68RkG96CT7t8YBkYjgxTmZHg4xxcUkg5qRiMAJCovqqagWo1OM4qcD/EVlQp7fJnKiqn3P/XaNHhTaiS140WqpwN5caZKnI8O3ZdQo41nkiaBaTQ18/xCJCVsgTbzXl6171SB8Iqm/bUjA2Mb2wcwwtxYp+iTGnGZ1jK0/oNRA+NbdZvMMGF1abN+1t8DGP6eNz6h6aQV7RJeaxfhAldar3ZRfoOgi/k/um8zCsBsDapfZCujp8fsR2MOlrCvu681L1/AMX/dBxGdltJTQTF9hwf/ie2xTKdUxrkNjY7UhOp8tJgPwQ5qa7g2sWohu8EXr4vDPlBnZxliirq/ea1MLt9j7P+mSGJeNNbVL7iTUNayMYw3ueiKyVYe+6am76/cIq03Jsn4AJZxRKs7bR4XCiSO2YZuVJx8Wfo7GFvp9uhBXEz5Fxn1MSax76Qnds1aRSYe/eANxIM+XZD2PMtbHtLzYwxGlztdn88rKdINMQCZLAZnYUX7j2TKzRcmz1TyvY+kgPrlZndETWCcLqrfY9sZCReAIbkVvwN6F0D39k=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
