travis:
  secure:
    BINSTAR_TOKEN: sodZpekrjJhVEZOehabbuDnB1mFoooEKvCoKsT+eow+kekoe0ySHpLWiw8vjxvcWkBf42dpEQVdOMRgTlFUkLaKkfOfQPARWqeFWm+2y84FOxIaWAXeXsGD2Y5B0Eaopt0zSSWGLK0/fNprssbeBGv8WlipsKGZ59CM+XHCFDavLlPvhvwqSa1oNNLUTaFAfqkhhVDYrseBhRXnKdt4R6u596ZD3xgcCF7iAifHb5nDBWk76u3nj2QzJh5+GxM1ac/zJFCQGf6Cu6Ja10t8HjTfLviBYx2l3EODLFpdDx/X9hSDAUewyjmzJL2YDjxiATRYpIyKjcF1v1kiQetmo3edUVicY0OJX5jA3Dd2ZBCCJDx3tOl0mQlVV3l1uuOoPLLi5hf6MrjlXQoMXf5/kqqgq5H5jySnQPPQ4r4RRQ7lc4uaVGQGtLuVRgM//pL7gZDcT2lKvUN4ILeMv5IkWB1u8NAlocfgm4iLWtWaCTpXXmZscNUlTktpkokxE+tlRwj1Z5uZfUutdIo+LS0XLawQrUDfPtEo94WgfngXyuDVCGplzte/ikv9AOY28QHpZPDj7z663ZDIoHD0g9zyP8NGfZwm4TAZsgU62iLmmgiWtH+CoMnud/aa+YDrboe7cp7XT/Snb4U6hTSE/m8poGKGO05wECnufFp9y4u+E8LE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
